### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by Oleg-feriss** [Oleg-feriss/homepage#4]
Скласти інтро (вступ), де в 2-4 реченнях описати, чим ти займаєшся, що подобається робити, що хочеться робити краще, що важливо робити, чому ти тут.

**Comment by EugeniusGR** [comment]
Інтро бомба

**Comment by Oleg-feriss** [comment]
Дякую тобі, сонце

**Comment by Oleg-feriss** [comment]
― I do not compete with others, the only competition that challenges me is myself. As a fighter, friend and an employee I am known as contemplative, tortured and driven. And I really like hitting people, so i hope the website will be really cool, BUGAGA!
