### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by Oleg-feriss** [Oleg-feriss/homepage#5]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by EugeniusGR** [comment]
мій номер тобі не дам

**Comment by Oleg-feriss** [comment]
Давай тоді хоть свою поштуXD

**Comment by Oleg-feriss** [comment]
Ryu Hoshi (リュウ Ryū)
https://www.facebook.com/profile.php?id=100004808958030
ryuwins@gmail.com
https://twitter.com/denjinryu
https://www.instagram.com/sworn_ryu/
